# Generated by Django 3.0.3 on 2020-03-27 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_client_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='in_facility',
            field=models.BooleanField(default=False),
        ),
    ]
