# Generated by Django 3.0.3 on 2020-04-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_client_in_facility'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnoTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=20)),
                ('group_name', models.CharField(max_length=20)),
                ('contact_number', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=35)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('type_of_business', models.CharField(max_length=50)),
                ('industry', models.CharField(max_length=30)),
                ('business_system', models.CharField(max_length=50)),
                ('instructor', models.CharField(max_length=30)),
                ('mentors', models.CharField(max_length=50)),
                ('mission', models.TextField()),
                ('vision', models.TextField()),
                ('tagline', models.TextField()),
                ('members', models.CharField(max_length=100)),
            ],
        ),
    ]
