# Generated by Django 3.0.3 on 2020-04-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_technoteam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technoteam',
            name='group_name',
            field=models.CharField(max_length=40),
        ),
    ]
