# Generated by Django 3.0.3 on 2020-04-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200401_1920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='balance',
            new_name='coins',
        ),
        migrations.AddField(
            model_name='client',
            name='internet',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='technoteam',
            name='coins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='technoteam',
            name='internet',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='technoteam',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='technoteam',
            name='team_image',
            field=models.ImageField(default=0, upload_to='media/'),
            preserve_default=False,
        ),
    ]
