# Generated by Django 3.0.3 on 2020-04-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20200401_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartUpTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_image', models.ImageField(upload_to='media/')),
                ('startup_name', models.CharField(max_length=20)),
                ('company_name', models.CharField(max_length=40)),
                ('founders', models.TextField()),
                ('main_address', models.CharField(max_length=500)),
                ('parent_company', models.CharField(max_length=100)),
                ('partner_company', models.CharField(max_length=350)),
                ('contact_number', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=35)),
                ('type_of_business', models.CharField(max_length=50)),
                ('industry', models.CharField(max_length=30)),
                ('business_system', models.CharField(max_length=50)),
                ('operating_start', models.TimeField()),
                ('operating_end', models.TimeField()),
                ('accelerators', models.TextField()),
                ('mission', models.TextField()),
                ('vision', models.TextField()),
                ('tagline', models.TextField()),
                ('employee_list', models.TextField()),
                ('internet', models.IntegerField(default=0)),
                ('coins', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='facility_logs',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='technoteam',
            name='members',
            field=models.TextField(),
        ),
    ]
