# Generated by Django 3.0.3 on 2020-04-10 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20200403_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=30)),
                ('incubatee', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('facilitator', models.CharField(max_length=100)),
                ('schedule', models.DateTimeField()),
                ('venue', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('attendees', models.CharField(max_length=250)),
                ('cost', models.IntegerField(default=0)),
                ('payment_mode', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('debcre', models.CharField(max_length=6)),
                ('category', models.CharField(max_length=100)),
                ('bookact', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('payment_mode', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='startupteam',
            name='startup_name',
            field=models.CharField(max_length=30),
        ),
    ]
