# Generated by Django 3.0.3 on 2020-04-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20200410_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=30)),
                ('amount', models.IntegerField()),
                ('date_transact', models.DateField()),
                ('remark', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=30)),
                ('source', models.CharField(max_length=75)),
                ('inv_type', models.CharField(max_length=30)),
                ('amount', models.IntegerField()),
                ('date_received', models.DateField()),
                ('remark', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=30)),
                ('amount', models.IntegerField()),
                ('date_received', models.DateField()),
                ('remark', models.TextField()),
            ],
        ),
    ]
