# Generated by Django 3.0.3 on 2020-02-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('purpose', models.CharField(choices=[('studying', 'Studying'), ('project making', 'Project Making'), ('group collaboration', 'Group Collaboration')], default='studying', max_length=30)),
                ('referenceNo', models.IntegerField()),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cap', models.IntegerField()),
                ('isSimultaneous', models.BooleanField(default=False)),
            ],
        ),
    ]
