# Generated by Django 3.0.3 on 2020-02-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='attendee',
            field=models.CharField(default='none', max_length=30),
        ),
    ]
