# Generated by Django 3.0.3 on 2020-02-29 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_attendee'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='computers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='venue',
            name='has_computers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venue',
            name='min_name',
            field=models.CharField(default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='purpose',
            field=models.CharField(choices=[('Studying', 'Studying'), ('Project Making', 'Project Making'), ('Group Collaboration', 'Group Collaboration')], default='Studying', max_length=30),
        ),
    ]
