# Generated by Django 3.0.3 on 2020-03-03 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20200302_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='cost',
            field=models.IntegerField(default=20),
        ),
    ]
