# Generated by Django 3.0.3 on 2020-03-03 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_venue_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='venue',
            field=models.CharField(choices=[('Conference Room A', 'Conference Room'), ('Conference Room B', 'Conference Room'), ('Joined Conference Room', 'Joined Conference Room'), ('Coworking Space', 'Coworking Space')], default='Coworking Space', max_length=30),
        ),
    ]
