# Generated by Django 3.0.3 on 2020-03-13 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_auto_20200313_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='bookDate',
            new_name='book_date',
        ),
    ]
