# Generated by Django 3.0.3 on 2020-03-21 15:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_auto_20200313_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='isSimultaneous',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='min_name',
        ),
        migrations.AlterField(
            model_name='booking',
            name='book_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 21, 23, 4, 2, 707398)),
        ),
    ]
