# Generated by Django 3.0.3 on 2020-03-27 05:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0019_auto_20200327_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='book_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 27, 13, 35, 43, 177735)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Booked', 'Booked'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed'), ('No Show', 'No Show'), ('Late', 'Late'), ('Overstayed', 'Overstayed')], default='Booked', max_length=30),
        ),
    ]
