# Generated by Django 3.0.3 on 2020-03-27 05:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0020_auto_20200327_1335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='over_min',
            new_name='time_stay',
        ),
        migrations.AlterField(
            model_name='booking',
            name='book_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 27, 13, 51, 36, 577246)),
        ),
    ]
