# Generated by Django 3.0.3 on 2020-03-27 06:07

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0022_auto_20200327_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='book_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 27, 14, 7, 31, 843572)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='computers',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Booked', 'Booked'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed'), ('No Show', 'No Show'), ('Late', 'Late'), ('Overstayed', 'Overstayed'), ('Cancelled by Admin', 'Cancelled by Admin')], default='Booked', max_length=30),
        ),
    ]
