# Generated by Django 3.0.3 on 2020-03-27 06:13

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0025_auto_20200327_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='book_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 27, 14, 13, 11, 757280)),
        ),
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='submit_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 27, 14, 13, 11, 758305)),
        ),
    ]
