# Generated by Django 3.0.3 on 2020-04-01 07:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0028_auto_20200327_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaxDaysOfBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_days', models.IntegerField(default=3)),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='book_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 1, 15, 1, 28, 494088)),
        ),
        migrations.AlterField(
            model_name='review',
            name='submit_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 1, 15, 1, 28, 494088)),
        ),
    ]
