# Generated by Django 3.0.3 on 2020-04-12 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0037_auto_20200412_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='book_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 12, 22, 36, 3, 519218)),
        ),
        migrations.AlterField(
            model_name='review',
            name='submit_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 12, 22, 36, 3, 523365)),
        ),
    ]
